// Mock data for Kolkata heritage sites and routes
import type { HeritageSite, Restaurant, HeritageQuest, RestaurantReview, Dish, User, Badge, UserBadge, CultureSubmission } from "./types"

export const mockHeritageSites: HeritageSite[] = [
  {
    id: "1",
    name: "Victoria Memorial",
    description:
      "An iconic marble building built in memory of Queen Victoria. A masterpiece of Indo-Saracenic architecture.",
    category: "Monument",
    latitude: 22.5448,
    longitude: 88.3426,
    address: "1 Queens Way, Kolkata 700071",
    entryFee: 250,
    openingHours: "10:00 AM - 6:00 PM",
    bestTimeToVisit: "October to March",
    historicalSignificance: "Constructed between 1872-1921, it's a symbol of the British Raj era",
    imageUrl: "/victoria-memorial-kolkata.jpg",
    rating: 4.8,
    visitCount: 15000,
  },
  {
    id: "2",
    name: "South Park Street Cemetery",
    description: "Historic cemetery with beautiful marble tombs dating back to 18th-19th centuries.",
    category: "Cemetery",
    latitude: 22.5486,
    longitude: 88.3711,
    address: "Park Street, Kolkata 700016",
    entryFee: 0,
    openingHours: "6:00 AM - 6:00 PM",
    bestTimeToVisit: "Early morning or late afternoon",
    historicalSignificance: "Hidden tomb featuring in Heritage Quests, dates back to 1787",
    imageUrl: "/south-park-street-cemetery-kolkata.jpg",
    rating: 4.5,
    visitCount: 8000,
  },
  {
    id: "3",
    name: "St. Paul's Cathedral",
    description: "Stunning neo-gothic cathedral with beautiful stained glass windows.",
    category: "Building",
    latitude: 22.5523,
    longitude: 88.3676,
    address: "Cathedral Road, Kolkata 700071",
    entryFee: 0,
    openingHours: "8:00 AM - 6:00 PM",
    bestTimeToVisit: "During morning prayers",
    historicalSignificance: "Oldest cathedral in India, built in the 19th century",
    imageUrl: "/st-pauls-cathedral-kolkata.jpg",
    rating: 4.6,
    visitCount: 6500,
  },
  {
    id: "4",
    name: "Jorasanko Tagore House",
    description: "Ancestral home of Rabindranath Tagore, now a museum showcasing his life and works.",
    category: "Museum",
    latitude: 22.579,
    longitude: 88.3661,
    address: "Jorasanko Lane, Kolkata 700007",
    entryFee: 150,
    openingHours: "10:30 AM - 5:00 PM",
    bestTimeToVisit: "Tuesday to Sunday",
    historicalSignificance: "Home of Bengal's greatest poet and first non-European Nobel laureate",
    imageUrl: "/jorasanko-tagore-house-kolkata.jpg",
    rating: 4.7,
    visitCount: 5000,
  },
  {
    id: "5",
    name: "Kalighat Temple",
    description: "Ancient Hindu temple dedicated to Goddess Kali, one of the holiest sites in Bengal.",
    category: "Temple",
    latitude: 22.5145,
    longitude: 88.3515,
    address: "Kalighat, Kolkata 700026",
    entryFee: 0,
    openingHours: "5:00 AM - 12:00 PM, 3:00 PM - 9:00 PM",
    bestTimeToVisit: "Early morning",
    historicalSignificance: "One of the 51 Shakti Peeths, mentioned in ancient texts",
    imageUrl: "/kalighat-temple-kolkata.jpg",
    rating: 4.4,
    visitCount: 12000,
  },
  {
    id: "6",
    name: "Indian Museum",
    description: "India's oldest museum with an extensive collection of art, history, and natural specimens.",
    category: "Museum",
    latitude: 22.5445,
    longitude: 88.3923,
    address: "27 Chowringhee Road, Kolkata 700071",
    entryFee: 500,
    openingHours: "10:00 AM - 5:00 PM",
    bestTimeToVisit: "Weekday mornings",
    historicalSignificance: "Founded in 1814, houses over 1 million artifacts",
    imageUrl: "/indian-museum-kolkata.jpg",
    rating: 4.5,
    visitCount: 4500,
  },
]

export const mockRestaurants: Restaurant[] = [
  {
    id: "r1",
    name: "Bhim Nag",
    description: "Traditional Bengali cuisine in a heritage setting near Victoria Memorial.",
    cuisineType: ["Bengali", "Indian"],
    latitude: 22.5448,
    longitude: 88.3426,
    address: "Near Victoria Memorial, Kolkata",
    priceRange: "moderate",
    rating: 4.6,
    reviewCount: 234,
    imageUrl: "/bhim-nag-restaurant-kolkata.jpg",
    avgCostPerPerson: 400,
    specialties: ["Hilsa Fish", "Luchi", "Aloo Posto"],
  },
  {
    id: "r2",
    name: "Flury's Tea Room",
    description: "Iconic establishment on Park Street serving pastries and tea since 1927.",
    cuisineType: ["Bakery", "Continental", "Tea"],
    latitude: 22.5528,
    longitude: 88.3652,
    address: "18 Park Street, Kolkata 700016",
    priceRange: "moderate",
    rating: 4.7,
    reviewCount: 567,
    imageUrl: "/flurys-tea-room-park-street.jpg",
    avgCostPerPerson: 300,
    specialties: ["Belgian Chocolate Cake", "Tea", "Sandwiches"],
  },
  {
    id: "r3",
    name: "Peter Cat",
    description: "Legendary restaurant known for its signature Chelo Kebab and continental cuisine.",
    cuisineType: ["Continental", "Indian", "Multi-cuisine"],
    latitude: 22.553,
    longitude: 88.367,
    address: "Park Street, Kolkata 700016",
    priceRange: "luxury",
    rating: 4.8,
    reviewCount: 789,
    imageUrl: "/peter-cat-park-street-kolkata.jpg",
    avgCostPerPerson: 800,
    specialties: ["Chelo Kebab", "Prawns Koobideh", "Mulligatawny Soup"],
  },
  {
    id: "r4",
    name: "Kali Tala",
    description: "Family-run Bengali restaurant with authentic home-cooked flavors.",
    cuisineType: ["Bengali"],
    latitude: 22.5145,
    longitude: 88.3515,
    address: "Near Kalighat, Kolkata 700026",
    priceRange: "budget",
    rating: 4.5,
    reviewCount: 156,
    imageUrl: "/kali-tala-restaurant-bengali-kolkata.jpg",
    avgCostPerPerson: 200,
    specialties: ["Machher Jhol", "Rice", "Mishti Doi"],
  },
  {
    id: "r5",
    name: "Aaheli",
    description: "Traditional Bengali restaurant in a restored heritage building.",
    cuisineType: ["Bengali", "Indian"],
    latitude: 22.579,
    longitude: 88.3661,
    address: "Near Jorasanko, Kolkata 700007",
    priceRange: "moderate",
    rating: 4.6,
    reviewCount: 312,
    imageUrl: "/aaheli-restaurant-jorasanko-kolkata.jpg",
    avgCostPerPerson: 450,
    specialties: ["Shorshe Ilish", "Chingri Malai Curry", "Payesh"],
  },
]

export const mockHeritageQuests: HeritageQuest[] = [
  {
    id: "q1",
    name: "Hidden Tomb Mystery",
    description: "Find the hidden tomb at South Park Street Cemetery to unlock a 10% discount at Flury's Tea Room.",
    heritageSiteId: "2",
    rewardPoints: 50,
    rewardDiscount: 10,
    difficultyLevel: "medium",
    clue: "Look for the oldest marble structure with intricate carvings near the eastern wall",
  },
  {
    id: "q2",
    name: "Victoria's Secrets",
    description: "Explore all sections of Victoria Memorial and complete 5 photo challenges.",
    heritageSiteId: "1",
    rewardPoints: 75,
    rewardDiscount: 15,
    difficultyLevel: "hard",
    clue: "Start from the main entrance and visit the museum galleries",
  },
  {
    id: "q3",
    name: "Cathedral Bells",
    description: "Attend a service at St. Paul's Cathedral and learn about its architecture.",
    heritageSiteId: "3",
    rewardPoints: 40,
    rewardDiscount: 8,
    difficultyLevel: "easy",
    clue: "Visit during morning prayers (8:00 AM)",
  },
]

export const mockRestaurantReviews: RestaurantReview[] = [
  {
    id: "rev1",
    restaurantId: "r1",
    userId: "user1",
    userName: "Arjun K.",
    rating: 5,
    text: "Authentic Bengali cuisine at its finest. The hilsa fish was perfectly cooked!",
    dishesTried: ["Hilsa Fish", "Luchi"],
    createdAt: new Date("2025-01-15"),
  },
  {
    id: "rev2",
    restaurantId: "r2",
    userId: "user2",
    userName: "Priya S.",
    rating: 5,
    text: "A heritage institution! The Belgian Chocolate Cake is to die for.",
    dishesTried: ["Belgian Chocolate Cake", "Tea"],
    createdAt: new Date("2025-01-14"),
  },
  {
    id: "rev3",
    restaurantId: "r3",
    userId: "user3",
    userName: "Vikram P.",
    rating: 5,
    text: "Best Chelo Kebab in Kolkata. Worth every penny for the experience.",
    dishesTried: ["Chelo Kebab"],
    createdAt: new Date("2025-01-13"),
  },
  {
    id: "rev4",
    restaurantId: "r4",
    userId: "user4",
    userName: "Sneha M.",
    rating: 4,
    text: "Cozy place with homemade feels. Machher Jhol was delicious and authentic.",
    dishesTried: ["Machher Jhol", "Rice", "Mishti Doi"],
    createdAt: new Date("2025-01-10"),
  },
]

export const mockDishes: Dish[] = [
  "Hilsa Fish",
  "Luchi",
  "Aloo Posto",
  "Belgian Chocolate Cake",
  "Tea",
  "Sandwiches",
  "Chelo Kebab",
  "Prawns Koobideh",
  "Mulligatawny Soup",
  "Machher Jhol",
  "Rice",
  "Mishti Doi",
  "Shorshe Ilish",
  "Chingri Malai Curry",
  "Payesh",
]

export const mockUsers: User[] = [
  {
    id: "user2",
    email: "priya@kolkata.com",
    fullName: "Priya Sharma",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
    bio: "Love exploring heritage sites and trying authentic Bengali cuisine",
    age: 26,
    gender: "Female",
    interests: ["Heritage", "Photography", "Bengali Cuisine", "Art"],
    travelStyle: "cultural",
    isSoloTraveler: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "user3",
    email: "vikram@kolkata.com",
    fullName: "Vikram Patel",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Vikram",
    bio: "Adventure seeker exploring Kolkata's hidden gems",
    age: 28,
    gender: "Male",
    interests: ["Adventure", "History", "Photography", "Food"],
    travelStyle: "adventurous",
    isSoloTraveler: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "user4",
    email: "sneha@kolkata.com",
    fullName: "Sneha Gupta",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sneha",
    bio: "Cultural enthusiast seeking meaningful connections",
    age: 24,
    gender: "Female",
    interests: ["Culture", "Museums", "Bengal Literature", "Spirituality"],
    travelStyle: "cultural",
    isSoloTraveler: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "user5",
    email: "arjun@kolkata.com",
    fullName: "Arjun Kumar",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun",
    bio: "Travel blogger documenting Kolkata stories",
    age: 29,
    gender: "Male",
    interests: ["Travel", "Blogging", "Heritage", "Street Food"],
    travelStyle: "cultural",
    isSoloTraveler: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockTravelMatches: Array<{
  id: string
  user1: User
  user2: User
  compatibilityScore: number
  commonInterests: string[]
}> = [
    {
      id: "match1",
      user1: mockUsers[0],
      user2: mockUsers[1],
      compatibilityScore: 92,
      commonInterests: ["Heritage", "Photography", "Food"],
    },
    {
      id: "match2",
      user1: mockUsers[0],
      user2: mockUsers[2],
      compatibilityScore: 85,
      commonInterests: ["Heritage", "Museums", "Culture"],
    },
    {
      id: "match3",
      user1: mockUsers[0],
      user2: mockUsers[3],
      compatibilityScore: 88,
      commonInterests: ["Heritage", "Travel", "Food"],
    },
  ]

export const mockBadges: Badge[] = [
  {
    id: "b1",
    name: "The Bhadralok",
    description: "Visited 5 heritage sites",
    iconUrl: "👑",
    requirementType: "visits",
    requirementValue: 5,
  },
  {
    id: "b2",
    name: "Heritage Master",
    description: "Visited 10 heritage sites",
    iconUrl: "🏛️",
    requirementType: "visits",
    requirementValue: 10,
  },
  {
    id: "b3",
    name: "Culinary Explorer",
    description: "Tried 5 different restaurants",
    iconUrl: "🍽️",
    requirementType: "restaurants",
    requirementValue: 5,
  },
  {
    id: "b4",
    name: "Social Butterfly",
    description: "Matched with 3 travel companions",
    iconUrl: "🦋",
    requirementType: "matches",
    requirementValue: 3,
  },
  {
    id: "b5",
    name: "Quest Master",
    description: "Completed 5 heritage quests",
    iconUrl: "⚔️",
    requirementType: "quests",
    requirementValue: 5,
  },
]

export const mockUserBadges: UserBadge[] = [
  {
    badge: mockBadges[0],
    unlockedAt: new Date("2025-01-10"),
    progress: 5,
  },
  {
    badge: mockBadges[2],
    unlockedAt: new Date("2025-01-12"),
    progress: 5,
  },
]

export const mockCultureSubmissions: CultureSubmission[] = [
  {
    id: "cs1",
    userId: "user2",
    userName: "Priya Sharma",
    title: "Durga Puja Pandal Art",
    description: "The intricate artwork at our local pandal during Durga Puja celebration. These are made by skilled artisans who spend months creating these masterpieces.",
    imageUrl: "/durga-puja-pandal.jpg",
    status: "approved",
    rewardPoints: 50,
    createdAt: new Date("2025-01-05"),
    reviewedAt: new Date("2025-01-06"),
  },
  {
    id: "cs2",
    userId: "user3",
    userName: "Vikram Patel",
    title: "Traditional Bengali Wedding",
    description: "A glimpse into the traditional Bengali wedding rituals. The bride wearing the iconic red and white saree with traditional jewelry.",
    imageUrl: "/bengali-wedding.jpg",
    status: "pending",
    rewardPoints: 50,
    createdAt: new Date("2025-01-20"),
  },
  {
    id: "cs3",
    userId: "user4",
    userName: "Sneha Gupta",
    title: "Street Food Culture",
    description: "The famous Kolkata street food - Puchka (Pani Puri) being prepared by a local vendor. This is an integral part of Kolkata's food culture.",
    imageUrl: "/kolkata-puchka.jpg",
    status: "rejected",
    rewardPoints: 50,
    createdAt: new Date("2025-01-15"),
    reviewedAt: new Date("2025-01-16"),
    adminNote: "Image quality too low, please resubmit with a clearer photo.",
  },
]
